#!/usr/bin/env python
# coding: utf-8

# In[1]:


import tweepy
from tweepy import OAuthHandler
import json
from timeit import default_timer as timer
import pandas as pd
import requests
import os


# In[2]:


# read csv file
df = pd.read_csv('twitter-archive-enhanced.csv')


# In[9]:


df.head()
